# Generated by Django 2.1.7 on 2019-03-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(default='中国', max_length=128)),
                ('birth', models.DateField(default='1991-01-01')),
                ('identify', models.CharField(choices=[('user', '用户'), ('root', '管理员')], default='用户', max_length=10)),
                ('image', models.ImageField(default='user/bochan50.png', upload_to='user', verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
